# Site settings
title: Sihuhata's Blog
email: speakingchinglish@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  欢迎来到我的个人博客，这里会分享我的想法、经验和学习心得。
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://freopen.com" # the base hostname & protocol for your site

# 导航菜单配置
navigation_links:
  - title: 首页
    url: /
  - title: 读书笔记
    url: /notes/
  - title: 碎碎念
    url: /moments/
  - title: 故事集
    url: /stories/
  - title: 分类
    url: /categories/
  - title: 标签
    url: /tags/
  - title: 关于
    url: /about/

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# 显示文章摘要
show_excerpts: false

collections:
  notes:
    output: true
    permalink: /notes/:path/
  moments:
    output: true
    permalink: /moments/:path/
  stories:
    output: true
    permalink: /stories/:path/

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/